apiVersion: v1
kind: Pod
metadata:
  name: pod-multiple-container
  labels:
    app: test-multiple-conatainer
    site: test
spec:
  containers:
    - name: nginx-container
      image: nginx:1.25.1
      ports:
        - containerPort: 80
    - name: whoami-container
      image: traefik/whoami
      ports:
        - containerPort: 81
      env:
        - name: WHOAMI_PORT_NUMBER
          value: "81"