apiVersion: v1
kind: Pod
metadata:
  name: scale-nginx-pod-1
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:1.25.1
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: scale-nginx-pod-2
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:1.25.1
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: scale-nginx-pod-3
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:1.25.1
      ports:
        - containerPort: 80
---