apiVersion: v1
kind: Service
metadata:
  name: test-node-port-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32010
  type: NodePort