apiVersion: v1
kind: Service
metadata:
  name: test-port-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 81
      targetPort: 80
    - protocol: TCP
      port: 82
      targetPort: 81

  type: ClusterIP