apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    owner: wasinee
spec:
  containers:
    - name: nginx-container
      image: nginx:1.25.1
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: whoami-pod
  labels:
    app: whoami
    owner: wasinee
spec:
  containers:
    - name: whoami-container
      image: traefik/whoami
      ports:
        - containerPort: 80
