apiVersion: v1
kind: Secret
metadata:
  name: basic-secret
type: Opaque
data:
  username: d2FzaW5lZQ==  # Base64-encoded username raw is : wasinee
  password: UEBzc3cwcmQ=  # Base64-encoded passwor  raw is : P@ssw0rd