apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  storageClassName: database-volume
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # อันนี้แล้วแต่ว่าคุณจะเอา mount ข้อมูลไว้ที่ไหน ของผม Mount ไว้ตามนี้
    # อาจจะติดเรื่องสิทธิ์ ผมแนะนำเปลี่ยนเป็นให้สิทธิ์หมดก่อน เพื่อใช้ในการทดลอง
    path: /root/k8s-data/database-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: database-volume
  resources:
    requests:
      storage: 2Gi